name: Run Selenium Tests with Allure

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install allure-pytest
          sudo apt-get install -y libnss3 libgconf-2-4
          sudo apt-get install -y google-chrome-stable
          sudo apt-get update
          sudo apt-get install -y unzip wget     
          pip install webdriver-manager

      - name: Run tests and generate Allure reports
        run: |
          pytest --alluredir=reports

     
          
