name: Run Selenium Tests with Allure

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install allure-pytest
          sudo apt-get install -y libnss3 libgconf-2-4
          sudo apt-get install -y google-chrome-stable
          sudo apt-get update
          sudo apt-get install -y unzip wget     
          pip install webdriver-manager

      - name: Run tests and generate Allure reports
        run: |
          pytest --alluredir=reports

      - name: Install Allure CLI
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.16.0/allure-commandline-2.16.0.zip
          unzip allure-commandline-2.16.0.zip -d allure
          export PATH=$PATH:$(pwd)/allure/allure-2.16.0/bin
        shell: bash
        
      - name: Print PATH and current directory
        run: |
          echo $PATH
          pwd

      - name: Generate Allure report
        run: |
          allure generate reports --clean -o allure-report
        shell: bash
        

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
          
